CC = g++
CFLAGS = -std=c++11 -Wall -Werror -Wno-sign-compare -Wno-unused-result -O3
FILES = main.cpp TLongArithm.cpp
PROG = da6

all:
	$(CC) $(CFLAGS) -o $(PROG) $(FILES)

clean:
	rm -f *.o $(PROG)