CC = g++
CFLAGS = -std=c++11 -Wall -Werror -Wno-sign-compare -Wno-unused-result -O3
FILES = da5.cpp TSuffTree.cpp
PROG = da5

all:
	$(CC) $(CFLAGS) -o $(PROG) $(FILES)

clean:
	rm -f *.o $(PROG)